Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using dotnetpractice.Services;
using dotnetpractice.Models;
using dotnetpractice.Models.ViewModels;

namespace dotnetpractice.Controllers
{
    public class CategoriesController : BaseController
    {
        public CategoriesController(WebsiteDbContext dbContext) : base(dbContext) { }

        public IActionResult Index()
        {
            IQueryable<Category> catList = categories.GetCategories();
            return View(catList.Select(a => new CategoriesVM()
            {
                Id = a.Id,
                Name = a.Name,
                Description = a.Description
            }).ToList());
        }

        [Route("Categories/{Id}")]
        public IActionResult Details(int Id)
        {
            Category cat = categories.GetCategory(Id);
            IQueryable<Product> productList = products.GetProducts(CategoryId: Id);
            CategoryProductsVM CatProducts = new CategoryProductsVM
            {
                Category = new CategoriesVM()
                {
                    Id = cat.Id,
                    Name = cat.Name,
                    Description = cat.Description
                },
                Products = productList.Select(a => new ProductsVM()
                {
                    Id = a.Id,
                    Name = a.Name,
                    Description = a.Description,
                    Price = a.Price,
                    Inventory = a.Inventory,
                    Image = a.Image,
                    Category = a.Category
                }).ToList()
            };
            return View(CatProducts);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using dotnetpractice.Models;
using dotnetpractice.Models.ViewModels;

namespace dotnetpractice.Controllers
{
    public class ProductsController : BaseController
    {
        public ProductsController(WebsiteDbContext dbContext) : base(dbContext) { }

        public IActionResult Index()
        {
            IQueryable<Product> productList = products.GetProducts();
            return View(productList.Select(a => new ProductsVM()
            {
                Id = a.Id,
                Name = a.Name,
                Description = a.Description,
                Price = a.Price,
                Inventory = a.Inventory,
                Image = a.Image,
                Category = a.Category
            }).ToList());
        }

        [Route("Products/{Id:int}")]
        public IActionResult Details(int Id)
        {
            Product product = products.GetProduct(Id);

            return View(new ProductsVM()
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                Inventory = product.Inventory,
                Category = product.Category
            });
        }

        [Route("Products/{Id:int}/Edit")]
        public IActionResult Edit(int Id)
        {
            Product product = products.GetProduct(Id);
            IQueryable<Category> catList = categories.GetCategories();

            return View(new ProductsVM()
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                Inventory = product.Inventory,
                Category = product.Category,
                Categories = catList.Select(a => new CategoriesVM()
                {
                    Id = a.Id,
                    Name = a.Name,
                    Description = a.Description
                }).ToList()
            });
        }

        public IActionResult New()
        {
            IQueryable<Category> catList = categories.GetCategories();
            
            return View(new ProductsVM()
            {
                Name = "",
                Description = "",
                Price = 0,
                Inventory = 1,
                Category = 1,
                Categories = catList.Select(a => new CategoriesVM()
                {
                    Id = a.Id,
                    Name = a.Name,
                    Description = a.Description
                }).ToList()
            });
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Shared/_Footer.cshtml
<hr />
<footer>
    <p>&copy; 2016 - DotnetPractice by Jesús Escamilla</p>
</footer>

Views/Shared/_Layout.cshtml
@using Newtonsoft.Json

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotnetPractice</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    @Html.Partial("_Nav")

    <div class="container body-content">
        @RenderBody()

        @Html.Partial("_Footer")
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/vue/vue-resource-min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    
    @if (Model != null)
    {
        <script>var viewModel = @Html.Raw(JsonConvert.SerializeObject(Model));</script>
    }
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Nav.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">dotnetpractice</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
            </ul>
        </div>
    </div>
</div>